[package]
name = "aurora_core"
version = "0.1.0"
edition = "2024"
description = "Types, math, color, rects, and other core utilities for Aurora."

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde"]

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "geometry_bench"
harness = false
