[package]
name = "widget_gallery_example"
version = "0.1.0"
edition = "2024"

[dependencies]
aurora_ui = { path = "../../aurora", features = ["wgpu_backend", "text", "animate", "svg", "syntax", "image"] }
aurora_theme = { path = "../../crates/aurora_theme" }
aurora_iconify = { path = "../../crates/aurora_iconify" }


[build-dependencies]
winresource = "0.1"
image = { version = "0.25", default-features = false, features = ["png", "ico"] }

[profile.release]
opt-level = "z"       # optimize for size
lto = "fat"           # link-time optimization
codegen-units = 1     # single codegen unit
panic = "abort"       # smaller panic handling
strip = "symbols"     # strip debug symbols