[package]
name = "aurora_platform"
version = "0.1.0"
edition = "2024"
description = "Windowing + native handle + event loop"

[dependencies]
aurora_core = { path = "../aurora_core" }
winit = "0.30"
log = "0.4"
aurora_gpu = { path = "../aurora_gpu", default-features = false }
aurora_render = { path = "../aurora_render" }
aurora_widgets = {path = "../aurora_widgets"}
aurora_text = {path = "../aurora_text", optional = true}
aurora_i18n = {path = "../aurora_i18n", optional = true}
aurora_a11y = { path = "../aurora_a11y", optional = true }
accesskit_winit = { version = "0.32", optional = true }
image = { version = "0.25", optional = true, default-features = false, features = ["png", "jpeg"] }
rfd = { version = "0.17", optional = true, default-features = false, features = ["xdg-portal"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_UI_Controls",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", features = ["NSWindow", "NSView"] }
objc2-foundation = { version = "0.3.2", features = ["NSObject"] }



[features]
default = ["software"]
software = ["aurora_gpu/software"]
opengl = ["aurora_gpu/opengl"]
wgpu_backend = ["aurora_gpu/wgpu_backend"]
text = ["dep:aurora_text", "aurora_render/text", "aurora_widgets/text"]
image = ["dep:image", "aurora_render/image", "aurora_widgets/image"]
svg = ["aurora_render/svg", "aurora_widgets/svg"]
a11y = ["dep:aurora_a11y", "dep:accesskit_winit", "aurora_widgets/a11y"]
dialogs = ["dep:rfd"]
i18n = ["dep:aurora_i18n"]