[package]
name = "custom_titlebar_example"
version = "0.1.0"
edition = "2024"
build="build.rs"

[dependencies]
aurora_ui = {path="../../aurora", features = ["software", "text", "image"]}

[build-dependencies]
winresource = "0.1"
image = { version = "0.25", default-features = false, features = ["png", "ico"] }
