//! Runtime profile switching for Aurora UI themes.
//!
//! This crate provides the minimal runtime needed for theming:
//! - A thread-local profile index switched via [`set_profile`]
//! - Re-exports of core types used by generated theme code
//!
//! All theme data (colors, edges, corners, values) lives as compile-time
//! `static` constants generated by the `aurora_theming::config!()` macro.
//! No JSON is parsed or stored at runtime.

// Re-export core types so the proc macro can reference them via aurora_theme::
pub use aurora_core;
pub use aurora_core::color::Color;
pub use aurora_core::geometry::corners::Corners;
pub use aurora_core::geometry::edges::Edges;

use std::cell::Cell;

thread_local! {
    static CURRENT_PROFILE: Cell<usize> = const { Cell::new(0) };
}

/// Sets the active profile by index.
pub fn set_profile(id: usize) {
    CURRENT_PROFILE.with(|c| c.set(id));
}

/// Returns the active profile index.
pub fn current_profile() -> usize {
    CURRENT_PROFILE.with(|c| c.get())
}
